---
# In this playbook, we will be copying files to our remote clients
- name: Copy Files Playbook
  hosts: all
  become: yes
  tasks:

    - name: Copy file1 to remote user's /tmp
      copy:
        src: /home/bob/file1
        dst: /tmp/backup-file1
        mode: '0644'
        owner: john
        group: john

    - name: Copy file1 with some more secure permissions
      copy:
        src: /home/bob/file1
        dst: /tmp/secure-backup-file1
        mode: u=rw,g=r
        owner: root
        group: john
