---
- name: Update remote user's passwords
  hosts: linuxservers
  become: yes

  tasks:
    - name: Update password with sha512 encryption
      user:
        name: john
        update_password: always
        password: "{{ newpass | password_hash('sha512') }}"


# Command: ansible-playbook update-user-password.yml --extra-vars newpass=abc12345
#
# The password parameter will create a variable called newpass, and then will
# encrypt the password as it gets sent to the remote clients. And the command will
# input the value, abc12345, to our variable.
#
# The reason for all of this is because Ansible does not allow us to pass clear-text
# passwords through the user module.